Repository sul-dlss/dor-services-client, pull requests merged in 2019-08, with the labels that each got.

#67 Provide a deprecation horizion
  lib/dor/services/client/object.rb
Labels: tech debt

#76 Add Client::Object#add_constituent (blocked by dor-services-app PR 321)
  README.md
  lib/dor/services/client.rb
  lib/dor/services/client/object.rb
  spec/dor/services/client/object_spec.rb
Labels: SDR Fall 2019, virtual merge

#82 hook up code coverage
  .travis.yml
  dor-services-client.gemspec
  spec/spec_helper.rb
Labels: SDR Fall 2019, tech debt
